#!/bin/bash

DEMO_DIR="$( dirname "${BASH_SOURCE[0]}" )"
ROOT_DIR="$( cd ${DEMO_DIR}/.. && pwd)"

. demo-magic

TYPE_SPEED=30
# PROMPT_AFTER=1
DEMO_PROMPT="☸️ $ "
NO_WAIT=1

function comment() {
  echo -e '\033[0;33m>>> '$1' <<<\033[0m'
  wait
}


comment "Instructions for preparing the environment"
echo "1. Connect to you aws account, this means that the credential file: ~/.aws/credentials exists"
echo "2. In this directory, create the file \"pull-secret\" that has your OpenShift pull secret (not a kube secret)"
echo "3. Connect to the OpenShift cluster to be used for Management of hypershift"

comment "Install hypershift"
pe "hypershift install"

comment "Deploy hypershift"
cd hyper
pe "./create-hypershift.sh jnp-next 4.9.0 -i m5.2xlarge -r 3 -s 35"
cd ..
